TRUNCATE dbgen_version;
TRUNCATE customer_address;
TRUNCATE customer_demographics;
TRUNCATE date_dim;
TRUNCATE warehouse;
TRUNCATE ship_mode;
TRUNCATE time_dim;
TRUNCATE reason;
TRUNCATE income_band;
TRUNCATE item;
TRUNCATE store;
TRUNCATE call_center;
TRUNCATE customer;
TRUNCATE web_site;
TRUNCATE store_returns;
TRUNCATE household_demographics;
TRUNCATE web_page;
TRUNCATE promotion;
TRUNCATE catalog_page;
TRUNCATE inventory;
TRUNCATE catalog_returns;   
TRUNCATE web_returns;
TRUNCATE web_sales;
TRUNCATE catalog_sales;     
TRUNCATE store_sales;

COPY dbgen_version FROM '/home/nminoru/git/github/tpcds-kit/tools/dbgen_version.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY customer_address FROM '/home/nminoru/git/github/tpcds-kit/tools/customer_address.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY customer_demographics FROM '/home/nminoru/git/github/tpcds-kit/tools/customer_demographics.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY date_dim FROM '/home/nminoru/git/github/tpcds-kit/tools/date_dim.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY warehouse FROM '/home/nminoru/git/github/tpcds-kit/tools/warehouse.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY ship_mode FROM '/home/nminoru/git/github/tpcds-kit/tools/ship_mode.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY time_dim FROM '/home/nminoru/git/github/tpcds-kit/tools/time_dim.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY reason FROM '/home/nminoru/git/github/tpcds-kit/tools/reason.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY income_band FROM '/home/nminoru/git/github/tpcds-kit/tools/income_band.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY item FROM '/home/nminoru/git/github/tpcds-kit/tools/item.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY store FROM '/home/nminoru/git/github/tpcds-kit/tools/store.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY call_center FROM '/home/nminoru/git/github/tpcds-kit/tools/call_center.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY customer FROM '/home/nminoru/git/github/tpcds-kit/tools/customer.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY web_site FROM '/home/nminoru/git/github/tpcds-kit/tools/web_site.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY store_returns FROM '/home/nminoru/git/github/tpcds-kit/tools/store_returns.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY household_demographics FROM '/home/nminoru/git/github/tpcds-kit/tools/household_demographics.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY web_page FROM '/home/nminoru/git/github/tpcds-kit/tools/web_page.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY promotion FROM '/home/nminoru/git/github/tpcds-kit/tools/promotion.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY catalog_page FROM '/home/nminoru/git/github/tpcds-kit/tools/catalog_page.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY inventory FROM '/home/nminoru/git/github/tpcds-kit/tools/inventory.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY catalog_returns FROM '/home/nminoru/git/github/tpcds-kit/tools/catalog_returns.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY web_returns FROM '/home/nminoru/git/github/tpcds-kit/tools/web_returns.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY web_sales FROM '/home/nminoru/git/github/tpcds-kit/tools/web_sales.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY catalog_sales FROM '/home/nminoru/git/github/tpcds-kit/tools/catalog_sales.dat' WITH (FORMAT 'csv', DELIMITER '|');
COPY store_sales FROM '/home/nminoru/git/github/tpcds-kit/tools/store_sales.dat' WITH (FORMAT 'csv', DELIMITER '|');

-- CREATE INDEX ON web_sales;
-- CREATE INDEX ON store_sales;
-- CREATE INDEX ON catalog_sales;

