BEGIN;

DROP TABLE IF EXISTS store_sales3 CASCADE;
DROP TABLE IF EXISTS store_returns3 CASCADE;
DROP TABLE IF EXISTS web_sales3 CASCADE;
DROP TABLE IF EXISTS web_returns3 CASCADE;
DROP TABLE IF EXISTS catalog_sales3 CASCADE;
DROP TABLE IF EXISTS catalog_returns3 CASCADE;

CREATE TABLE web_sales3
(
    ws_sold_date_sk           integer                       ,
    ws_sold_time_sk           integer                       ,
    ws_ship_date_sk           integer                       ,
    ws_item_sk                integer               not null,
    ws_bill_customer_sk       integer                       ,
    ws_bill_cdemo_sk          integer                       ,
    ws_bill_hdemo_sk          integer                       ,
    ws_bill_addr_sk           integer                       ,
    ws_ship_customer_sk       integer                       ,
    ws_ship_cdemo_sk          integer                       ,
    ws_ship_hdemo_sk          integer                       ,
    ws_ship_addr_sk           integer                       ,
    ws_web_page_sk            integer                       ,
    ws_web_site_sk            integer                       ,
    ws_ship_mode_sk           integer                       ,
    ws_warehouse_sk           integer                       ,
    ws_promo_sk               integer                       ,
    ws_order_number           integer               not null,
    ws_quantity               integer                       ,
    ws_wholesale_cost         decimal(7,2)                  ,
    ws_list_price             decimal(7,2)                  ,
    ws_sales_price            decimal(7,2)                  ,
    ws_ext_discount_amt       decimal(7,2)                  ,
    ws_ext_sales_price        decimal(7,2)                  ,
    ws_ext_wholesale_cost     decimal(7,2)                  ,
    ws_ext_list_price         decimal(7,2)                  ,
    ws_ext_tax                decimal(7,2)                  ,
    ws_coupon_amt             decimal(7,2)                  ,
    ws_ext_ship_cost          decimal(7,2)                  ,
    ws_net_paid               decimal(7,2)                  ,
    ws_net_paid_inc_tax       decimal(7,2)                  ,
    ws_net_paid_inc_ship      decimal(7,2)                  ,
    ws_net_paid_inc_ship_tax  decimal(7,2)                  ,
    ws_net_profit             decimal(7,2)                  ,
    ws_diff_date_sk           integer                       ,
    primary key (ws_item_sk, ws_order_number)
);

CREATE TABLE catalog_sales3
(
    cs_sold_date_sk           integer                       ,
    cs_sold_time_sk           integer                       ,
    cs_ship_date_sk           integer                       ,
    cs_bill_customer_sk       integer                       ,
    cs_bill_cdemo_sk          integer                       ,
    cs_bill_hdemo_sk          integer                       ,
    cs_bill_addr_sk           integer                       ,
    cs_ship_customer_sk       integer                       ,
    cs_ship_cdemo_sk          integer                       ,
    cs_ship_hdemo_sk          integer                       ,
    cs_ship_addr_sk           integer                       ,
    cs_call_center_sk         integer                       ,
    cs_catalog_page_sk        integer                       ,
    cs_ship_mode_sk           integer                       ,
    cs_warehouse_sk           integer                       ,
    cs_item_sk                integer               not null,
    cs_promo_sk               integer                       ,
    cs_order_number           integer               not null,
    cs_quantity               integer                       ,
    cs_wholesale_cost         decimal(7,2)                  ,
    cs_list_price             decimal(7,2)                  ,
    cs_sales_price            decimal(7,2)                  ,
    cs_ext_discount_amt       decimal(7,2)                  ,
    cs_ext_sales_price        decimal(7,2)                  ,
    cs_ext_wholesale_cost     decimal(7,2)                  ,
    cs_ext_list_price         decimal(7,2)                  ,
    cs_ext_tax                decimal(7,2)                  ,
    cs_coupon_amt             decimal(7,2)                  ,
    cs_ext_ship_cost          decimal(7,2)                  ,
    cs_net_paid               decimal(7,2)                  ,
    cs_net_paid_inc_tax       decimal(7,2)                  ,
    cs_net_paid_inc_ship      decimal(7,2)                  ,
    cs_net_paid_inc_ship_tax  decimal(7,2)                  ,
    cs_net_profit             decimal(7,2)                  ,
    cs_diff_date_sk           integer                       ,    
    primary key (cs_item_sk, cs_order_number)
);

CREATE TABLE store_sales3
(
    ss_sold_date_sk           integer                       ,
    ss_sold_time_sk           integer                       ,
    ss_item_sk                integer               not null,
    ss_customer_sk            integer                       ,
    ss_cdemo_sk               integer                       ,
    ss_hdemo_sk               integer                       ,
    ss_addr_sk                integer                       ,
    ss_store_sk               integer                       ,
    ss_promo_sk               integer                       ,
    ss_ticket_number          integer               not null,
    ss_quantity               integer                       ,
    ss_wholesale_cost         decimal(7,2)                  ,
    ss_list_price             decimal(7,2)                  ,
    ss_sales_price            decimal(7,2)                  ,
    ss_ext_discount_amt       decimal(7,2)                  ,
    ss_ext_sales_price        decimal(7,2)                  ,
    ss_ext_wholesale_cost     decimal(7,2)                  ,
    ss_ext_list_price         decimal(7,2)                  ,
    ss_ext_tax                decimal(7,2)                  ,
    ss_coupon_amt             decimal(7,2)                  ,
    ss_net_paid               decimal(7,2)                  ,
    ss_net_paid_inc_tax       decimal(7,2)                  ,
    ss_net_profit             decimal(7,2)                  ,
    ss_diff_date_sk           integer                       ,        
    primary key (ss_item_sk, ss_ticket_number)
);

CREATE TABLE store_returns3
(
    sr_returned_date_sk       integer                       ,
    sr_return_time_sk         integer                       ,
    sr_item_sk                integer               not null,
    sr_customer_sk            integer                       ,
    sr_cdemo_sk               integer                       ,
    sr_hdemo_sk               integer                       ,
    sr_addr_sk                integer                       ,
    sr_store_sk               integer                       ,
    sr_reason_sk              integer                       ,
    sr_ticket_number          integer               not null,
    sr_return_quantity        integer                       ,
    sr_return_amt             decimal(7,2)                  ,
    sr_return_tax             decimal(7,2)                  ,
    sr_return_amt_inc_tax     decimal(7,2)                  ,
    sr_fee                    decimal(7,2)                  ,
    sr_return_ship_cost       decimal(7,2)                  ,
    sr_refunded_cash          decimal(7,2)                  ,
    sr_reversed_charge        decimal(7,2)                  ,
    sr_store_credit           decimal(7,2)                  ,
    sr_net_loss               decimal(7,2)                  ,
    sr_dummy                  text                          ,            
    primary key (sr_item_sk, sr_ticket_number)
);

CREATE TABLE catalog_returns3
(
    cr_returned_date_sk       integer                       ,
    cr_returned_time_sk       integer                       ,
    cr_item_sk                integer               not null,
    cr_refunded_customer_sk   integer                       ,
    cr_refunded_cdemo_sk      integer                       ,
    cr_refunded_hdemo_sk      integer                       ,
    cr_refunded_addr_sk       integer                       ,
    cr_returning_customer_sk  integer                       ,
    cr_returning_cdemo_sk     integer                       ,
    cr_returning_hdemo_sk     integer                       ,
    cr_returning_addr_sk      integer                       ,
    cr_call_center_sk         integer                       ,
    cr_catalog_page_sk        integer                       ,
    cr_ship_mode_sk           integer                       ,
    cr_warehouse_sk           integer                       ,
    cr_reason_sk              integer                       ,
    cr_order_number           integer               not null,
    cr_return_quantity        integer                       ,
    cr_return_amount          decimal(7,2)                  ,
    cr_return_tax             decimal(7,2)                  ,
    cr_return_amt_inc_tax     decimal(7,2)                  ,
    cr_fee                    decimal(7,2)                  ,
    cr_return_ship_cost       decimal(7,2)                  ,
    cr_refunded_cash          decimal(7,2)                  ,
    cr_reversed_charge        decimal(7,2)                  ,
    cr_store_credit           decimal(7,2)                  ,
    cr_net_loss               decimal(7,2)                  ,
    cr_dummy                  text                          ,    
    primary key (cr_item_sk, cr_order_number)
);

CREATE TABLE web_returns3
(
    wr_returned_date_sk       integer                       ,
    wr_returned_time_sk       integer                       ,
    wr_item_sk                integer               not null,
    wr_refunded_customer_sk   integer                       ,
    wr_refunded_cdemo_sk      integer                       ,
    wr_refunded_hdemo_sk      integer                       ,
    wr_refunded_addr_sk       integer                       ,
    wr_returning_customer_sk  integer                       ,
    wr_returning_cdemo_sk     integer                       ,
    wr_returning_hdemo_sk     integer                       ,
    wr_returning_addr_sk      integer                       ,
    wr_web_page_sk            integer                       ,
    wr_reason_sk              integer                       ,
    wr_order_number           integer               not null,
    wr_return_quantity        integer                       ,
    wr_return_amt             decimal(7,2)                  ,
    wr_return_tax             decimal(7,2)                  ,
    wr_return_amt_inc_tax     decimal(7,2)                  ,
    wr_fee                    decimal(7,2)                  ,
    wr_return_ship_cost       decimal(7,2)                  ,
    wr_refunded_cash          decimal(7,2)                  ,
    wr_reversed_charge        decimal(7,2)                  ,
    wr_account_credit         decimal(7,2)                  ,
    wr_net_loss               decimal(7,2)                  ,
    wr_dummy                  text                          ,
    primary key (wr_item_sk, wr_order_number)
);

INSERT INTO store_sales3
SELECT
    CASE WHEN ss_sold_date_sk IS NOT NULL THEN ss_sold_date_sk + diff_data_sk ELSE null END,
    ss_sold_time_sk,
    ss_item_sk,
    ss_customer_sk,
    ss_cdemo_sk,
    ss_hdemo_sk,
    ss_addr_sk,
    ss_store_sk,
    ss_promo_sk,
    ss_ticket_number + diff_number,
    ss_quantity,
    ss_wholesale_cost,
    ss_list_price,
    ss_sales_price,
    ss_ext_discount_amt,
    ss_ext_sales_price,
    ss_ext_wholesale_cost,
    ss_ext_list_price,
    ss_ext_tax,
    ss_coupon_amt,
    ss_net_paid,
    ss_net_paid_inc_tax,
    ss_net_profit,
    null
FROM store_sales2, generator_parameter;

INSERT INTO web_sales3
SELECT
    CASE WHEN ws_sold_date_sk IS NOT NULL THEN ws_sold_date_sk + diff_data_sk ELSE null END,
    ws_sold_time_sk,
    CASE WHEN ws_ship_date_sk IS NOT NULL THEN ws_ship_date_sk + diff_data_sk ELSE null END,
    ws_item_sk,
    ws_bill_customer_sk,
    ws_bill_cdemo_sk,
    ws_bill_hdemo_sk,
    ws_bill_addr_sk,
    ws_ship_customer_sk,
    ws_ship_cdemo_sk,
    ws_ship_hdemo_sk,
    ws_ship_addr_sk,
    ws_web_page_sk,
    ws_web_site_sk,
    ws_ship_mode_sk,
    ws_warehouse_sk,
    ws_promo_sk,
    ws_order_number + diff_number,
    ws_quantity,
    ws_wholesale_cost,
    ws_list_price,
    ws_sales_price,
    ws_ext_discount_amt,
    ws_ext_sales_price,
    ws_ext_wholesale_cost,
    ws_ext_list_price,
    ws_ext_tax,
    ws_coupon_amt,
    ws_ext_ship_cost,
    ws_net_paid,
    ws_net_paid_inc_tax,
    ws_net_paid_inc_ship,
    ws_net_paid_inc_ship_tax,
    ws_net_profit,
    null
FROM web_sales2, generator_parameter;

INSERT INTO catalog_sales3
SELECT
    CASE WHEN cs_sold_date_sk IS NOT NULL THEN cs_sold_date_sk + diff_data_sk ELSE null END,
    cs_sold_time_sk,
    CASE WHEN cs_ship_date_sk IS NOT NULL THEN cs_ship_date_sk + diff_data_sk ELSE null END,
    cs_bill_customer_sk,
    cs_bill_cdemo_sk,
    cs_bill_hdemo_sk,
    cs_bill_addr_sk,
    cs_ship_customer_sk,
    cs_ship_cdemo_sk,
    cs_ship_hdemo_sk,
    cs_ship_addr_sk,
    cs_call_center_sk,
    cs_catalog_page_sk,
    cs_ship_mode_sk,
    cs_warehouse_sk,
    cs_item_sk,
    cs_promo_sk,
    cs_order_number + diff_number,
    cs_quantity,
    cs_wholesale_cost,
    cs_list_price,
    cs_sales_price,
    cs_ext_discount_amt,
    cs_ext_sales_price,
    cs_ext_wholesale_cost,
    cs_ext_list_price,
    cs_ext_tax,
    cs_coupon_amt,
    cs_ext_ship_cost,
    cs_net_paid,
    cs_net_paid_inc_tax,
    cs_net_paid_inc_ship,
    cs_net_paid_inc_ship_tax,
    cs_net_profit,
    null
FROM catalog_sales2, generator_parameter;

INSERT INTO store_returns3    
SELECT
    S.sr_returned_date_sk + diff_data_sk,
    S.sr_return_time_sk,
    S.sr_item_sk,
    S.sr_customer_sk,
    S.sr_cdemo_sk,
    S.sr_hdemo_sk,
    S.sr_addr_sk,
    S.sr_store_sk,
    S.sr_reason_sk,
    S.sr_ticket_number + diff_number,
    S.sr_return_quantity,
    S.sr_return_amt,
    S.sr_return_tax,
    S.sr_return_amt_inc_tax,
    S.sr_fee,
    S.sr_return_ship_cost,
    S.sr_refunded_cash,
    S.sr_reversed_charge,
    S.sr_store_credit,
    S.sr_net_loss,
    null
FROM store_returns2 S, generator_parameter;

INSERT INTO catalog_returns3
SELECT
    C.cr_returned_date_sk + diff_data_sk,
    C.cr_returned_time_sk,
    C.cr_item_sk,
    C.cr_refunded_customer_sk,
    C.cr_refunded_cdemo_sk,
    C.cr_refunded_hdemo_sk,
    C.cr_refunded_addr_sk,
    C.cr_returning_customer_sk,
    C.cr_returning_cdemo_sk,
    C.cr_returning_hdemo_sk,
    C.cr_returning_addr_sk,
    C.cr_call_center_sk,
    C.cr_catalog_page_sk,
    C.cr_ship_mode_sk,
    C.cr_warehouse_sk,
    C.cr_reason_sk,
    C.cr_order_number + diff_number,
    C.cr_return_quantity,
    C.cr_return_amount,
    C.cr_return_tax,
    C.cr_return_amt_inc_tax,
    C.cr_fee,
    C.cr_return_ship_cost,
    C.cr_refunded_cash,
    C.cr_reversed_charge,
    C.cr_store_credit,
    C.cr_net_loss,
    null
FROM catalog_returns2 C, generator_parameter;

INSERT INTO web_returns3
SELECT
    W.wr_returned_date_sk + diff_data_sk,
    W.wr_returned_time_sk,
    W.wr_item_sk,
    W.wr_refunded_customer_sk,
    W.wr_refunded_cdemo_sk,
    W.wr_refunded_hdemo_sk,
    W.wr_refunded_addr_sk,
    W.wr_returning_customer_sk,
    W.wr_returning_cdemo_sk,
    W.wr_returning_hdemo_sk,
    W.wr_returning_addr_sk,
    W.wr_web_page_sk,
    W.wr_reason_sk,
    W.wr_order_number + diff_number,
    W.wr_return_quantity,
    W.wr_return_amt,
    W.wr_return_tax,
    W.wr_return_amt_inc_tax,
    W.wr_fee,
    W.wr_return_ship_cost,
    W.wr_refunded_cash,
    W.wr_reversed_charge,
    W.wr_account_credit,
    W.wr_net_loss,
    null
FROM web_returns2 W, generator_parameter;

END;
