FROM ahanaio/prestodb-sandbox

COPY ./app/etc/config.properties                 /opt/presto-server/etc/config.properties
COPY ./app/etc/keystore.jks                      /opt/presto-server/etc/keystore.jks
COPY ./app/etc/passwd.db                         /opt/presto-server/etc/passwd.db
COPY ./app/etc/password-authenticator.properties /opt/presto-server/etc/password-authenticator.properties
