version: "3.7"

services:
  myjupyter:
    image: myjupyter
    build:
      context: .
      dockerfile: Dockerfile-jupyternotebook
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: myjupyter/{{.Name}}/{{.ID}}

  localdns-dnsmasq:
    image: localdns-dnsmasq
    build:
      context: localdns-dnsmasq
    cap_add:
      - NET_ADMIN
    domainname: example.com
    hostname: host
    extra_hosts:
      - "*.host.example.com:127.0.0.1"
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  localdns-bind:
    image: localdns-bind
    build:
      context: localdns-bind
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
