FROM jupyter/scipy-notebook

USER root

RUN mkdir -p /var/log/supervisor

RUN echo "${NB_USER}:password" | chpasswd
RUN gpasswd -a "${NB_USER}" sudo

RUN echo "c.NotebookApp.token = ''" >> ./.jupyter/jupyter_notebook_config.py

USER $NB_UID
