FROM centos:7

MAINTAINER nminoru1975@gmail.com

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
#   rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN echo -e "root:root" | chpasswd

RUN yum install -y httpd httpd-tools mailcap apr apr-util mod_auth_kerb rsyslog bind-utils krb5-workstation krb5-libs less curl

COPY ./kdc/krb5.conf      /etc/krb5.conf
COPY ./http/kerberos.conf /etc/httpd/conf.d/
RUN rm /etc/httpd/conf.d/welcome.conf
RUN mkdir /var/www/html/kerberos/

RUN systemctl enable rsyslog.service
RUN systemctl enable httpd.service

EXPOSE 80
EXPOSE 443

VOLUME [ "/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]
