version: "3.7"

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile
      target: namenode
    networks:
      - network1
    ports:
      - 8020:8020
      - 9000:9000
      - 9870:9870
      - 9871:9871
      - 50100:50100
      - 50105:50105
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  datanode:
    build:
      context: .
      dockerfile: Dockerfile
      target: datanode
    networks:
      - network1
    ports:
      - 9864:9864
      - 9865:9865
      - 9866:9866
      - 9867:9867
      - 50475:50475
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

networks:
  network1:
    name: mynetwork
