services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole1234567890
      POSTGRES_USER: guacamole_user
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    environment:    
      GUACD_LOG_LEVEL: debug
#    volumes:
#      - ./guacd/guacamole:/var/lib/guacamole

  guacamole:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres      
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user      
      POSTGRES_PASSWORD: guacamole1234567890
      TOTP_ENABLED: false
#   volumes:
#     - ./guacamole/extensions:/etc/guacamole/extensions
#     - ./guacamole/server.xml:/usr/local/tomcat/conf/server.xml
#     - ./guacd/guacamole:/var/lib/guacamole
    depends_on:
      - postgres
      - guacd
